
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HORA = 14;
  public static final int LIST_EVENTOS = 4;
  public static final int COMA = 6;
  public static final int LIST_ESPACIO = 2;
  public static final int NOM_TIPOS = 11;
  public static final int LLAVE_FIN = 9;
  public static final int LIST_TIPOS = 3;
  public static final int EOF = 0;
  public static final int FECHA = 13;
  public static final int IGUAL = 5;
  public static final int error = 1;
  public static final int LLAVE_APR = 8;
  public static final int PUNTOCOMA = 7;
  public static final int NOM_ESPACIOS = 10;
  public static final int NOM_EVENTOS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LIST_ESPACIO",
  "LIST_TIPOS",
  "LIST_EVENTOS",
  "IGUAL",
  "COMA",
  "PUNTOCOMA",
  "LLAVE_APR",
  "LLAVE_FIN",
  "NOM_ESPACIOS",
  "NOM_TIPOS",
  "NOM_EVENTOS",
  "FECHA",
  "HORA"
  };
}

